spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student
    username: suman
    password: suman
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
          format_sql: true

server:
  error:
    include-message: always